Project_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from homeapp import sitemaps
from homeapp.sitemaps import BlogpostSitemap
from django.views.generic import TemplateView   #This is for robots.txt

sitemaps={'blogpost':BlogpostSitemap}



urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('',include('homeapp.urls')), 
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}),
    path('robots.txt',TemplateView.as_view(template_name='robots.txt',content_type='text/plain')),
    path('account/',include('account.urls')),
    path('blog/',include('blog.urls')),
    
]

#For accessing media files on admin pannel like open image in full size after clicking on it

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path,include
from .import views
from homeapp.views import search_result 


urlpatterns = [

    path('profile/',views.profile,name='profile'),
    path('addblog/', views.add_blog, name='addblog'),
    path('confirm_logout/',views.confirm_logout, name='confirmlogout'),
    path('logout/',views.logoutme,name='logout'),
    path('search/',search_result),
    path('delete_account/<int:pk>',views.DeleteAccount.as_view(), name='deleteaccount'),
    #add profile detail
    path('add_detail', views.add_profile_detail,name='adddetail'),
    path('edit_profile_detail/<int:pk>',views.EditProfileDetail.as_view(),name='editprofiledetail'),
    #show user data
    path('profiledetail/<str:username>', views.Show_User_Data, name='profiledetail'),

]

homeapp/urls.py
from django.urls import path,include
from .import views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from blog.models import blogpost

app_name='homeapp'



urlpatterns = [
    
    path('',views.index,name='home'),
    path('about', views.about, name='about'),
    path('privacy-policy', views.privacy_policy,name='privacypolicy'),
    path('search/',views.search_result,name='search'),
    path('listdata/',views.ListData.as_view(),name='listdata'),
    path('article/<slug:slug>',views.DetailData.as_view(),name='article'),
    path('editdata/<slug:slug>', login_required(views.EditBlog.as_view(template_name='edit_blog.html')), name='editblog'),
    path('deleteblog/<slug:slug>/remove',views.DeleteBlog.as_view(),name='deleteblog'),
    path('user_blogs/', views.user_blogs.as_view(), name='user_blogs'),
    #path('category/', views.category_list.as_view(),name='category'),  #perfomr link operation on index.html
    path('like/<slug:slug>', views.like_post, name='like_post'),
    path('article/<slug:slug>/comment', views.comment_view, name='comment'),
    path('article/<slug:slug>/deletecomment/<int:pk>', views.delete_comment, name='deletecomment'),


]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import related
from django.urls import reverse

from django.db.models.signals import pre_save
from django.utils.text import slugify
from ckeditor.fields import RichTextField
# Create your models here.

class blogpost(models.Model):
   
    created_by=models.ForeignKey(User,on_delete=models.CASCADE,related_name='bloguser')
    topic=models.CharField(max_length=122,null=False)
    title=models.TextField(blank=False)
    slug=models.SlugField(max_length=250,null=True)
    post=RichTextField(blank=True, null=True)
    #post=models.TextField()
    #more other headings and their text which can only be added from admin pannel
    likes=models.ManyToManyField(User, related_name='blog_posts',blank=True)
    date=models.DateTimeField(auto_now_add=True )

    class Meta:
        ordering=['-date']
    
    def __str__(self):
        return ' (' +str(self.created_by)+') Title- '+self.title[:30]
    
    def get_absolute_url(self):
        return reverse('homeapp:article', kwargs={'slug':self.slug})
    
def create_slug(instance, new_slug=None):
    slug=slugify(instance.title)
    if new_slug is not None:
        slug=new_slug
    qs=blogpost.objects.filter(slug=slug).order_by('-id')
    exists=qs.exists()
    if exists:
        new_slug="%s-%s" %(slug,qs.first().id)
        return create_slug(instance,new_slug=new_slug)
    return slug


def pre_save_blog_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug= create_slug(instance)

pre_save.connect(pre_save_blog_reciever,sender=blogpost)   
    


class CommentModel(models.Model):
    post = models.ForeignKey(blogpost ,related_name='comments', on_delete=models.CASCADE)
    name = models.ForeignKey(User,related_name='userdetail', on_delete=models.CASCADE)
    body = models.TextField()
    comment_likes=models.ManyToManyField(User, related_name='comment_post')
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering=['-date_added']
    
    def __str__(self):
        return '%s - %s' %(self.post.title[:30], self.name)



#User Profile detail
#function for profile picture file name in media root
def profile_picture_filename(instance, filename):
    return 'images/profile_pictures/{0}/{1}'.format(instance.profile_name, filename)


class ProfileModel(models.Model):
    profile_name=models.OneToOneField(User, on_delete=models.CASCADE)
    full_name=models.CharField(max_length=200,blank=True,null=True)
    profile_picture= models.ImageField(upload_to=profile_picture_filename, blank=True, null=True)
    bio=models.TextField(blank=True,null=True)
    facebook_url=models.CharField(max_length=200,blank=True,null=True)
    instagram_url=models.CharField(max_length=200,blank=True,null=True)

    def __str__(self):
        return str(self.profile_name)+" ("+(self.full_name)+")"

blog/forms.py
from django import forms
from .models import blogpost , ProfileModel


class Myblogform(forms.ModelForm):
    choices=(('','Select Topic'),('Educational','Educational'),('Informational','Informational'),('Funny Thoughts/Jokes','Funny Thoughts/Jokes'),
    ('About Me','About Me'),('Sayri','Sayri'),('Other','Other'))
    topic=forms.ChoiceField(choices=choices,widget=forms.Select(attrs={'class':'form-control'}),required=True)
    
    
    class Meta:
        model=blogpost
        fields=['topic','title','post']
        widgets={'title':forms.TextInput(attrs={'class':'form-control'}),'post':forms.Textarea(attrs={'class':'form-control'})}


class ProfileForm(forms.ModelForm):
    class Meta:
        model=ProfileModel
        fields=['full_name','profile_picture', 'bio', 'facebook_url', 'instagram_url']
        widgets={'full_name':forms.TextInput(attrs={'class':'form-control'}),'bio':forms.Textarea(attrs={'class':'form-control'}),'facebook_url':forms.TextInput(attrs={'class':'form-control'}),'instagram_url':forms.TextInput(attrs={'class':'form-control'})}

blog/views.py
from django.contrib.auth.models import User
from django.http.response import HttpResponse
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from .models import blogpost,ProfileModel
from django.views.generic import DeleteView,UpdateView
from django.shortcuts import get_object_or_404
from .forms import Myblogform, ProfileForm
from django.utils.decorators import method_decorator

# Create your views here.

@login_required(login_url='login')
def profile(request):
    count=0

    postdata=blogpost.objects.all().filter(created_by=request.user)
    #print(list(postdata))
    
    count=len(postdata)
    
    fulldata=postdata[:2]  #Printing only current blog on the profile

    postdata=postdata[:8]  #Pring total 15 blogs title from first blog

    #Accessing profile detail from ProfileModel of user
    
    profile_detail=ProfileModel.objects.all().filter(profile_name=request.user)

    return render(request,'profile.html' ,{'data':postdata,'fulldata':fulldata,'count':count,"profile_detail":profile_detail})



@login_required(login_url='login')
def add_blog(request):
    fm=Myblogform()
    if request.method=='POST':
        fm=Myblogform(request.POST)
        if fm.is_valid():
            topic=fm.cleaned_data['topic']
            title=fm.cleaned_data['title']
            post=fm.cleaned_data['post']
            obj=blogpost(topic=topic,title=title,post=post)
    
            obj.created_by=request.user  #this line fill the created_by column in models by current username automatically
            obj.save()
            return redirect('profile')
    return render(request, 'add_blog.html',{'form':fm})

@login_required(login_url='login')
def confirm_logout(request):
    return render(request, 'confirm_logout.html')

@login_required(login_url='login')
def logoutme(request):
    logout(request)
    return redirect('/')

class DeleteAccount(DeleteView):
    model=User
    template_name='confirm_delete_account.html'
    success_url= reverse_lazy('home')


#Add user profile detail
@login_required(login_url='login')
def add_profile_detail(request):
    form=ProfileForm()
    if request.method=="POST":
        form=ProfileForm(request.POST,request.FILES)
        if form.is_valid():
            full_name=form.cleaned_data['full_name']
            profile_picture=form.cleaned_data['profile_picture']
            bio=form.cleaned_data['bio']
            facebook_url=form.cleaned_data['facebook_url']
            instagram_url=form.cleaned_data['instagram_url']
            obj=ProfileModel(full_name=full_name, profile_picture=profile_picture, bio=bio, facebook_url=facebook_url,instagram_url=instagram_url)
            obj.profile_name=request.user
            obj.save()
            return redirect('profile')
    return render(request, 'add_profile_detail.html',{'form':form})


#Update the user profile
@method_decorator(login_required, name='dispatch')
class EditProfileDetail(UpdateView):
    model=ProfileModel
    form_class=ProfileForm
    template_name='add_profile_detail.html'
    success_url=reverse_lazy('profile')

#View for showing any user data
def Show_User_Data(request,username):
    user=get_object_or_404(User, username=username)
    if ProfileModel.objects.all().filter(profile_name=user):
        data=get_object_or_404(ProfileModel,profile_name=user.id)
        bloglinks=blogpost.objects.all().filter(created_by=user.id)
        args={'user':user,'data':data,'bloglinks':bloglinks}
        return render(request, 'profile_detail.html',args)
    else:
        return HttpResponse(f'{user.username} Not updated Profile yet!')

blog/templates/add_blog.html
{%extends 'base.html'%}




{%block body%}

    <div class='container'>           
                        <h3>Create a Blog</h3><br>

                    
                        <!--This is the form for blog post-->
                        <div class='table-responsive'>
                        <form method='post' class='form-group'>

                            {%csrf_token%}
                            
                                {{form.media}}
                                 {{form.as_p}}
                            

                                <input type='submit' class='btn btn-primary' value='Post'>

                            </form>
                            </div>
            </div><br><br><br><br>

{%endblock%}

{%block footer%}
{%endblock%}

blog/templates/add_profile_detail.html
{%extends 'base.html'%}

{%block title%}User Detail{%endblock%}

{%block style%}

{%endblock%}

{%block body%}

    <div class='container'>
        <div class='table-responsive'>
        <form method='POST' enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}
            {%if not data%}
            <input type="submit" value='Save' class='btn-primary'>
            {%endif%}
        </form>
        </div>
    </div>

{%endblock%}

blog/templates/confirm_delete_account.html
{%extends 'base.html' %}



{%block body%}
    <div class='container'>
        {%if user.is_authenticated%}
        <strong>Confirmation </strong><br>
        <p class='text-muted'>You want to delete your account</p>
        
            <form method='post'>
            {%csrf_token%}
            <input type='submit' value='Yes' class='btn btn-danger'> &nbsp; &nbsp;
            <a class='btn btn-primary' href={%url 'profile' %}>No</a>
            </form>

        
        {%endif%}

    </div>

{%endblock%}


  
{%block footer%}

{%endblock%}

blog/templates/confirm_logout.html
{%extends 'base.html'%}


{%block body%}
    
    <div class='container'>
        {%if user.is_authenticated%}
        <strong>Confirmation </strong><br>
        <p class='text-muted'>You want to Logout your account</p>
        
            <a class='btn btn-danger' href={%url 'logout'%}>Yes</a> &nbsp;&nbsp;

        <a class='btn btn-primary' href={%url 'profile' %}>No</a>
        {%endif%}

    </div>
{%endblock%}

{%block footer%}

{%endblock%}

blog/templates/profile.html
{%extends 'base.html'%}


    {%block title%} Profile |  {{user.username}} {%endblock%}

{%block style%}
    a{text-decoration:none;}

    .userdropdown{padding:0px;
                    }
    .innerdropdown li{font-size:15px;
                    padding:5px;
                    }
    .postdata{word-wrap:break-word;}
    .bodycontainer{margin-bottom:100px;}
    
@media screen and (max-width:700px){
.username{font-size:17px;}
.card img{height:120px;width:110px;}


    
}

{%endblock%}


{%block body%}
    

      
<div class='container'>
    <div class='row'>
        <div class='col-md-10'>
        <!--Showing The user details-->
            {%for data in profile_detail%}
                <div class="card mb-3" >
                    <div class="row no-gutters">
                        <div class="col-md-2">
                            <!--if profile picture exist-->
                            {%if data.profile_picture%}
                                <img src={{data.profile_picture.url}} class="card-img" alt="{{data.profile_name}} image" height="140">
                            {%else%}
                                No image
                            {%endif%}
                        </div>
                        <div class="col-md-8">
                        <div class="card-body">
                            {%if data.full_name%}
                                <h5 class="card-title">{{data.full_name}}</h5>
                            {%endif%}

                            {%if data.facebook_url%}
                                <a href={{data.facebook_url}}>facebook</a>
                            {%endif%}
                            {%if data.instagram_url%}
                                | <a href={{data.instagram_url}} class='text-danger'>instagram</a>
                            {%endif%}<br><br>
                            {%if data.bio%}
                            <p class="card-text">{{data.bio | truncatechars:150}}</p>
                            {%endif%}  
                        </div>
                        </div>
                    </div>
                </div>
            
            {%endfor%}
        </div>
        <div class='col-md-2'>
            
            <nav class="navbar navbar-expand-lg navbar-light userdropdown">
                <ul class="list-group me-auto mb-2 mb-lg-0 ">
                    
                    <li class="nav-item dropdown list-group-item userdropdown bg-light">
                        <a class="nav-link dropdown-toggle text-dark username" href="#" id="navbarDropdown"  data-bs-toggle="dropdown" aria-expanded="false">
                            <strong>{{user}}</strong>
                        </a>
                        <ul class="dropdown-menu innerdropdown" aria-labelledby="navbarDropdown">
                        {%if profile_detail%}
                            {%for data in profile_detail%}
                            <li class='list-group-item'><a class="dropdown-item" href={%url 'editprofiledetail' data.id %}>Profile Settings</a></li>
                            {%endfor%}
                        {%else%}
                        <li class='list-group-item'><a class="dropdown-item" href={%url 'adddetail'%}>Profile Settings</a></li>
                        {%endif%}
                            <li class='list-group-item'><a class="dropdown-item" href={%url 'addblog'%}>Add Blog</a></li>
                            <li class='list-group-item'><a class="dropdown-item" href={%url 'confirmlogout' %}>Logout</a></li>
                           
                            <li class='list-group-item'> <a class="dropdown-item text-danger" href={%url 'deleteaccount' user.id %}>Delete Account</a></li>
                        </ul>
                    </li>
                </ul>
      
            </nav>
        </div>
  </div>    
</div><hr>

<div class='container mt-5 bodycontainer'>
    
    <div class='row'>
        <!--This is for  the profile webpage full data on middle of webpage -->
        <div class='col-md-8'>
            {%if fulldata%}
                {%for data in fulldata%}

                <div class='container bg-light p-2 postdata'>                                    
                    <h4><a href={%url 'homeapp:article' data.slug %}>{{data.title}}</a></h4>
                   <small class='text-muted'><b>Author: </b>{{data.created_by}}<br>
                    <b>Posted on: </b>{{data.date}}<br>
                    <b><u>Category: </b>{{data.topic}}</u></small><br><br>
                    <p class='lead'>{{data.post|safe | truncatechars:250 | linebreaks}} </p> 
                                                            
                    </p>
                    <small>{{data.likes.count}} likes</small> ,

                   <small> {{data.comments.count}} Comments</small>
                </div>  <br>                          

                {%endfor%}
            {% endif %}
            
            
        </div>

        <div class='col-md-1'>
        
        </div><br>
        <div class='col-md-3'>
        <h5>blogs</h5>

            {%if data%}
                {%for data in data%}
                               
                                    
                <a href={%url 'homeapp:article' data.slug%}> {{data.title | truncatechars:50}}</a><br><br>
                                    
                              
                {%endfor%}
            {%endif%}
            {%if data%}
            <a href={%url 'homeapp:user_blogs' %} class='text-info'>See all blogs</a>
            {%endif%}
            <hr> 
                                    
   
        </div>
                    
    </div><br><br>      
</div>
   
{%endblock%}

blog/templates/profile_detail.html
{%extends 'base.html'%}

{%block title%}{{data.profile_name}} | Profile{%endblock%}

{%block style%}

@media screen and (max-width:700px){

.card img{height:130px;width:110px;}
}

{%endblock%}

{%block body%}

<div class='container'>    
        
   <div class="card mb-3" >
                    <div class="row no-gutters">
                        <div class="col-md-2">
                            <!--if profile picture exist-->
                            {%if data.profile_picture%}
                                <img src={{data.profile_picture.url}} class="card-img" alt="{{data.profile_name}}profile picture" height="160">
                            {%endif%}
                        </div>
                        <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{data.full_name}}</h5>
                            <h6 class='text-muted'>({{data.profile_name}})</h6>
                            <p class="card-text">{{data.bio}}</p>
                            {%if data.facebook_url%}
                                <a href={{data.facebook_url}}>facebook</a>
                            {%endif%}
                            {%if data.instagram_url%}
                                | <a href={{data.instagram_url}} class='text-danger'>instagram</a>
                            {%endif%}
                        </div>
                        </div>
                    </div>
    </div>
    <br>
    <div class='allLinks'>
        <h3>All my blogs</h3>
        {%for data in bloglinks%}
            <a href={%url 'homeapp:article' data.slug %}>{{data.title}}</a><small class='text-muted'> ({{data.date}} )</small><br><br>
        {%endfor%}


    </div>

   

</div>
{%endblock%}