Project_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from homeapp import sitemaps
from homeapp.sitemaps import BlogpostSitemap
from django.views.generic import TemplateView   #This is for robots.txt

sitemaps={'blogpost':BlogpostSitemap}



urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('',include('homeapp.urls')), 
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}),
    path('robots.txt',TemplateView.as_view(template_name='robots.txt',content_type='text/plain')),
    path('account/',include('account.urls')),
    path('blog/',include('blog.urls')),
    
]

#For accessing media files on admin pannel like open image in full size after clicking on it

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path,include
from .import views
from homeapp.views import search_result 


urlpatterns = [

    path('profile/',views.profile,name='profile'),
    path('addblog/', views.add_blog, name='addblog'),
    path('confirm_logout/',views.confirm_logout, name='confirmlogout'),
    path('logout/',views.logoutme,name='logout'),
    path('search/',search_result),
    path('delete_account/<int:pk>',views.DeleteAccount.as_view(), name='deleteaccount'),
    #add profile detail
    path('add_detail', views.add_profile_detail,name='adddetail'),
    path('edit_profile_detail/<int:pk>',views.EditProfileDetail.as_view(),name='editprofiledetail'),
    #show user data
    path('profiledetail/<str:username>', views.Show_User_Data, name='profiledetail'),

]

homeapp/urls.py
from django.urls import path,include
from .import views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from blog.models import blogpost

app_name='homeapp'



urlpatterns = [
    
    path('',views.index,name='home'),
    path('about', views.about, name='about'),
    path('privacy-policy', views.privacy_policy,name='privacypolicy'),
    path('search/',views.search_result,name='search'),
    path('listdata/',views.ListData.as_view(),name='listdata'),
    path('article/<slug:slug>',views.DetailData.as_view(),name='article'),
    path('editdata/<slug:slug>', login_required(views.EditBlog.as_view(template_name='edit_blog.html')), name='editblog'),
    path('deleteblog/<slug:slug>/remove',views.DeleteBlog.as_view(),name='deleteblog'),
    path('user_blogs/', views.user_blogs.as_view(), name='user_blogs'),
    #path('category/', views.category_list.as_view(),name='category'),  #perfomr link operation on index.html
    path('like/<slug:slug>', views.like_post, name='like_post'),
    path('article/<slug:slug>/comment', views.comment_view, name='comment'),
    path('article/<slug:slug>/deletecomment/<int:pk>', views.delete_comment, name='deletecomment'),


]

templates/about.html
{%extends 'base.html'%}
{%load static%}


{%block style%}
    
{%endblock%}

{%block body%}
    <div class='container'>
        <div class='row'>
            <div class='col-md-2'>
                <img src={%static 'img/ropic.jpg'%} class='img-responsive' height='150'><br><br>
            </div>
            <div class='col-md-5 border '>
                <strong class='h2'>Rohit Kumar</strong>
                <p class='text-info mt-2'> <b>rk221377@gmail.com</b><br><br>
                <a href='https://www.github.com/Rohitkumar15697'><img src={%static 'img/github.png'%} height='22px' width='22px'> Github</a>
                , <a href='https://www.linkedin.com/in/rohit-kumar-b-tech-python-sql-html-django-8ba801186'><img src={%static 'img/linkedin.png'%} height='20px' width='20px'> Linkedin</a>
            </div>
        </div>
    </div>
{%endblock%}

{%block footer%}
{%endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!--Adding google adsense-->
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5962240393273120"
  crossorigin="anonymous"></script>
     
  <meta name='viewport' content="width=device-width, initial-scale=1">
  <meta charset="UTF-8">
    <link rel='stylesheet' href={%static 'css/bootstrap.min.css' %}>
    <script src={%static 'js/bootstrap.min.js' %}></script>
    <script src={%static 'js/jquery.min.js' %}></script>

  {%block head%}
  {%endblock%}

    <title>{% block title %} {% endblock %}</title>


       

    
    
    <style>
      body{padding:0px;margin:0px;}
      .bodyclass{margin-bottom:150px;}
      .headernav{background-color:rgb(253, 250, 250); transition: background-color 1s;;}
      .headernav:hover{background-color:rgb(245, 241, 241);}

      .headernav ul li a{margin:5px;}
      .footer{opacity:0.95;
            height:80px;
          position:fixed;
        bottom:0;
        
      }
    
      
    a{text-decoration:none;}
    a:hover{color:purple;}

    {%block style%}
    
    {%endblock%}

     @media screen and (max-width:700px){
       nav{font-size:19px;}
       .navbar-brand{font-size:28px;}
     }
    </style>
</head>
<body>
    {%url 'homeapp:home' as home%}
    {%url 'homeapp:about' as about%}
    {%url 'profile' as profile%}
    {%url 'register' as register%}
    {%url 'login' as login%}


    <!--Header part of the home page with navigation-->

    <nav class="navbar navbar-expand-lg navbar-light headernav" >
  <div class="container-fluid">
    <a class='navbar-brand fs-1 fw-bold' style="color:rgb(39, 161, 39);" href={{home}}>SpeaksEra</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"  >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse navbarhover" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-5">
        <li class="nav-item"><a class='nav-link' {%if request.path == home%} style="color:purple;"{%endif%} aria-current="page" href={{home}}>Home</a></li>
        
        {% if not user.is_authenticated%}
          <li class='nav-item' ><a class='nav-link' {%if request.path == about %} style="color:purple;"{%endif%} href={{about}}>About</a></li>
        {%endif%}

        {%if user.is_authenticated %}
            <li class='nav-item'><a class='nav-link' {%if request.path == profile %} style="color:purple;"{%endif%} href={{profile}}> Profile</a></li>
            
        
           {%else%}             
            
            <li class='nav-item'><a class='nav-link' {%if request.path == register%} style="color:purple;"{%endif%} href={{register}}>Register </a></li>
            <li class='nav-item'><a class='nav-link' {%if request.path == login%} style="color:purple;"{%endif%} href={{login}}>Login </a></li>

        {%endif%}
           
      </ul>
      <!--This is the search bar in webpage-->
      <form method='get' class='d-flex pt-3' action='/search' >

            <input type='text' class='form-control me-2' name='search_me' placeholder='Search'>
            <input type='submit' value='Search' class='btn btn-outline-success btn-sm'>
                                        
        </form>
    </div>
  </div>
</nav>




<div class='container-fluid mt-3 bodyclass'>
    {%block body%}



    {% endblock %}
    
    
</div>




{%block footer%}
<div class="container-fluid bg-dark text-light footer">
    <div style='margin-left:50px;padding-top:5px;'>
      &copy; Copyright 2021 All rights reserved<br>    
      <a href={%url 'homeapp:privacypolicy' %}>   Privacy Policy</a>      
    </div>
  </div>
{%endblock%}

</body>
</html>

templates/blogpost_detail.html
{%extends 'base.html' %}

    {%block head%} 
        <meta name='description' content="{{data.post}} | speaksera">
     {%endblock%}
    {%block title%} {{data.title}} | speaksera {%endblock%}

    {%block style%}
       
        .postdata{text-align:justify; 
            justify-content:space-between;
                    }
        

        .postdata h1{color:rgb(115, 132, 167)}
      
        .comment_section{display:flex;}
      /**This is the front of comment user image like circle**/
       .dot{        
                width:37px;
                border-radius:50%;
                text-align:center;
                font-size:23px;
                color:rgb(255, 250, 250);
                background:rgb(199, 199, 199);}
        .dotdata{margin-top:2px;margin-left:5px;}

        .btn-sm{font-size:12px;}
    {%endblock%}

    


{%block body%}



    <!--Showing detail data on the template-->
    <div class='container-fluid bg-light'>
        <div class='row'>
        

        <div class='col-md-9 postdata'>
            <h1>{{data.title}} | speaksera</h1>
            
            <small class='text-muted'><b>Author</b></small></b>
            
            <a href={%url "profiledetail" data.created_by %}><small class='text-info'>- {{data.created_by}}</small></a>
            
            <br>
            <!--Printing date of created-->
            <small class='text-muted'l><b>Posted on: </b>- {{data.date}}</small> <br>
            <!--topic of the blog--> 
            <small class='text-muted'><u><b>Category: </b>{{data.topic}}</u></small> 
            <!--actual blog post text, safe is used for ckeditor-->
            <div>   
                <p class='fs-5 fw-light'>{{data.post | safe | linebreaks}}</p>
            </div> 

                <hr><br>
                <!--Blog Like section-->
                
                {%if user.is_authenticated%}        
                                <form method='post' action="{%url 'homeapp:like_post' data.slug %}" class='form-group'>
                                                            
                                    {%csrf_token%}

                                    {%if user in data.likes.all%}
                                        <small>{{data.likes.count}} Likes</small> <button type='submit' name='like' value="{{data.slug}}" class='btn btn-danger  btn-sm'>Unlike</button>
                                    {%else%}
                                        <small>{{data.likes.count}} Likes</small> <button type='submit' name='like' value="{{data.slug}}" class='btn btn-primary btn-sm'>Like</button>
                                    {%endif%}

                                </form>
                    {%else%}
                        <small>{{data.likes.count}} Likes</small>
                        
                                
                {%endif%}  

            <br>    


                <!--This is for delete and edit post in blogpost_detail page only-->

                
                {% if user.is_authenticated %}
                    {%if user.id == data.created_by.id %}

                                <a href={%url 'homeapp:editblog' data.slug %}>Edit</a>&nbsp;&nbsp;&nbsp;

                                <a href={%url 'homeapp:deleteblog' data.slug%} class='text-danger'>Delete</a>

                    {%endif%}
                {%endif%}<br><br><hr>

        </div>


        
        <div class='col-md-3'>
            
            <strong>See also</strong><br><br>
            {%for titles in list_titles%}
                <a href={%url 'homeapp:article' titles.slug%}>{{titles.title | truncatechars:50}}</a><br><br>
            {%endfor%}
        
            <u><a  href={%url 'homeapp:listdata' %} class='text-info'>See all</a></u>
            
        </div>

        </div>
    </div>





        <br><br>    

        <!--Comments Section-->
        <hr>
        <div class='container'>
            <h2>Comments...</h2><br>



                {%if user.is_authenticated%}
                            <div class='col-md-6'>
                                <form method='post' action="{%url 'homeapp:article' data.slug %}/comment">
                                    {%csrf_token%}
                                    <div class='form-group'>
                                        
                                        <input type='text' name='comment_text' class='form-control' placeholder='comment...'>
                                        <input type='submit' name='comment_button' value='Post' class='btn btn-primary btn-sm mt-2'>
                                    </div>
                                </form>
                            </div>
                        
                {%endif%}
                <br>
                <div class='col-md-6'>
                <!--showing comment on page-->
                {%if not data.comments.all %}
                    <!--if there is no comments-->
                    No comments yet...

                    {%else%}
                        <!--if there is already some comments-->
                        <strong>Total Comments</strong> - {{data.comments.count}}
                        
                        <br>

                        <!--print all comments to template-->
                        {%for comment in data.comments.all %}
                        <div class='comment_section my-4'>
                            <div class='dot'>
                             {{ comment.name|make_list|first|title }}
                            </div>
                            <!--comment-by user name-->
                            <div class='dotdata'>
                                    
                                        <a href={%url "profiledetail" comment.name %}><strong>{{comment.name}}</strong></a>-
                                
                                <span class='text-muted'>{{comment.date_added}}</span>
                                
                            </div>
                            
                        </div>
                        <p style="margin-left:40px;margin-top:-20px;">{{comment.body}}</p>
                            
                        
                        <!--delete comment link: who can delete the comment commentor itself or blog owner-->
                        {%if user.is_authenticated and comment.name == user or user.is_authenticated and data.created_by == user %}
                        
                                <a class='btn btn-sm btn-danger'
                                style='padding:3px; float:right;margin-top:-40px;' href="{%url 'homeapp:article' data.slug %}/deletecomment/{{comment.id}}">Delete</a>
                        
                        {%endif%}
                        
                            <hr><br>
                        {%endfor%}
                        
                {%endif%}
                </div>
        </div>
        
            

    </div>


    
<br>
{%endblock%}

templates/blogpost_list.html
{%extends 'base.html'%}

    {%block title%} All Data{%endblock%}


    {%block style%}

    
        {%endblock%}




{%block body%}


    <div class='container'>
        <p class='h2'>List of all blogs</p><br>
            {%if blogpost_list%}
            
                {%for data in blogpost_list%}

              
                    

                    <p ><a href={%url 'homeapp:article' data.slug %}>{{data.title}}</a>
                    <small class='text-muted'> <b> Author: </b>{{data.created_by}} </small><br>
                    <small class='text-muted'> <b> Category: </b>{{data.topic}}</small></p>   

                {%endfor%}

      {%endif%}

        <!--Pagination for all blogs in list view page-->
      {% if is_paginated %}
        <nav aria-label="Page navigation conatiner">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
                {% endif %}
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

                {% endif %}
            </ul>
        </nav>
       &laquo;&laquo; <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
    {% endif %}
        

        </div><br>
 

    {%endblock%}

templates/delete_blog.html
{%extends 'base.html'%}
{%block title%}Delete blog {%endblock%}


<!--Start styling block-->
{%block style%}

{%endblock%}
<!--End style block-->


{%block body%}

    <div class='container'>
    {%if user.is_authenticated%}
            {% if user.id == blogpost.created_by.id %}   
        <strong>Confirmation </strong><br>
        <p class='text-muted'>Delete Blog</p>
        
            <form method='post'>
            {%csrf_token%}
            <input type='submit' value='Yes' class='btn btn-danger'>
            </form>

        <a class='btn btn-primary' href={%url 'homeapp:article' blogpost.slug %}>No</a>
        

        


            {%endif%}
    {%endif%}

</div>
{%endblock%}
{%block footer%}

{%endblock%}

templates/edit_blog.html
{%extends 'base.html' %}
<html lang="en">
<head>

   {%block title%}Edit Blog {%endblock%}
   
   {%block style%}
        
   {%endblock%}


{%block body%}


    <div class='container table-responsive'>

        {% if user.is_authenticated %}
                {% if user.id == blogpost.created_by.id %}

                <form method='post'>

                    {%csrf_token%}
                    {{form.media}}
                    {{form}}
                        <br><input type='submit' class='btn btn-primary' value='Push Edit'>

                    </form>

                    {%else%}

                        You are not authenticated to edit this blog
                {%endif%}


            {%else%}
                No allowed
                
        {% endif %}

    </div>
        
    
    {%endblock%}

{%block footer%}
{%endblock%}

templates/index.html
{%extends 'base.html'%}
{%load static%}

    {%block title%} Speaksera | Home {%endblock%}

    

    {%block style%}

    .carousel-inner{height:70vh;}
    .carousel-inner img{height:70vh;width:100%;}
    .carousel-item{transition:transform 1s;}
    .carousel-item:hover{transform:scale(0.98);}
    .ropic img{transition:transform 1s;}
    .ropic img:hover{transform:scale(0.9);}
    .postdata{word-wrap:break-word;}  
    
    .black-body{margin-top:80px;
                height:50vh;
                text-align:center;
                color:rgb(249, 255, 251);
                background-color:rgb(14, 8, 8);}
    .bodycontainer{margin-top:50px;}


    @media screen and (max-width:700px){
        .carousel-inner{height:65vh;}
        .carousel-inner img{height:30vh;width:100%;}
        .intro-text{margin-top:-250px}

    }
           
  
    {%endblock%}




{%block body%}


<div class='container main'>
        <div class='carousel slide carousel-slide' data-bs-ride='carousel' id='carouselslide'>

            <div class='carousel-inner'>

                <div class='carousel-item'>
                    <img src={%static './img/home-office-569359_1920.jpg' %} class='d-block'>
                    
                </div>
                <div class='carousel-item active'>
                    <img src={%static './img/mockup-863469_1920.jpg' %} class='d-block'>
                </div>
                <div class='carousel-item'>
                    <img src={%static './img/office-581131_1920.jpg' %} class='d-block'>
                </div>
                <div class='carousel-item'>
                    <img src={%static './img/pencils-762555_1920.jpg' %} class='d-block'>
                </div>

            </div>

            
                <div class='intro-text'>
                    <br><br>
                    <h2  style='text-align:center;color:red;'>Introduction to <span style='color:rgb(32, 177, 32);'>SpeaksEra</span></h2><br>
                    <p class='text-muted'>Put your views on the site and share your thoughts with all over the world.
                    This website is in testing phase so other updates will be visible every day or in a week.
                        
                        <a href={% url 'register' %}>Create account Now!</a> 
                    </p>
                    
                    <strong>New Updates:</strong>
                    <p class='text-muted'>You can delete your posted comment and your blog comments also</p>

                </div>

        </div>
    

<!--black part in block body-->
<div class='container-fluid black-body'><br>
    <h1>SpeaksEra</h1>
    <p>Reading is the great skill</p>
    <p>Read what you likes use your valuable time at good place</p>
    <p>Speaksera is a place where you read everything you want to read</p>
    <p>You can also show your writing skills in this place</p>
    <p>We cares for you and your time</p> 
    
</div>




<div class='container bodycontainer'>
    <div class='row'>
        {%if blog_data%}
        <div class='col-md-8'>                            
            {%for data in blog_data%}                          
                <div class='container mt-5 p-2 bg-light postdata'>    
                    <h5><a href={%url 'homeapp:article' data.slug%}> {{data.title}}</a></h5>
                    <small class='text-muted'>
                    <b>Posted on: </b>{{data.date}}<br>
                    <b><u>Category: </b>{{data.topic}}</u></small><br>
                    <p class='lead'>{{data.post|safe | truncatechars:250 | linebreaks}} </p> 
                    <small>{{data.likes.count}} likes</small> ,
                   <small> {{data.comments.count}} Comments</small>

                </div>       <hr>               
            {%endfor%}
                                
        </div>
        {% endif %}

       <div class='col-md-1'></div>             

        <div class='col-md-3'>

                        
            <br><strong>All Blogs</strong><br><br>

            {%if data%}
                {%for data in data%}
                                    
                           
                    <p> <a href={%url 'homeapp:article' data.slug%}> {{data.title | truncatechars:50}} </a></p>
                        
                                     
                {%endfor%}

            {%endif%}
            <a  href={%url 'homeapp:listdata' %} class='text-info'>See all blogs</a>
        </div>

    </div>        
</div>
    
<br><br>

    <!-- Another container    -->


    <div class='container'>
        <div class='row'>
            <div class='col-md-4'>
                
            </div>
            <div class='col-md-4 ropic'>
            <a href={{about}}><img src={%static "img/ropic.jpg"%} height='100' width='90' style='border-radius:50%;margin-left:80px;'></a>
            </div>
            <div class='col-md-4'>
            
            </div>

        </div>

    </div>
</div>


    {%endblock%}

    
    

templates/privacy_policy.html
{%extends 'base.html'%}



{%block body%}
    <h1>Privacy Policy for speaksera</h1>

<p>At speaksera, accessible from www.speaksera.com, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by speaksera and how we use it.</p>

<p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>

<p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in speaksera. This policy is not applicable to any information collected offline or via channels other than this website. Our Privacy Policy was created with the help of the <a href="https://www.privacypolicygenerator.info/">Privacy Policy Generator</a>.</p>

<h2>Consent</h2>

<p>By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>

<h2>Information we collect</h2>

<p>The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information.</p>
<p>If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide.</p>
<p>When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number.</p>

<h2>How we use your information</h2>

<p>We use the information we collect in various ways, including to:</p>

<ul>
<li>Provide, operate, and maintain our website</li>
<li>Improve, personalize, and expand our website</li>
<li>Understand and analyze how you use our website</li>
<li>Develop new products, services, features, and functionality</li>
<li>Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes</li>
<li>Send you emails</li>
<li>Find and prevent fraud</li>
</ul>

<h2>Log Files</h2>

<p>speaksera follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.</p>

<h2>Cookies and Web Beacons</h2>

<p>Like any other website, speaksera uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.</p>

<p>For more general information on cookies, please read <a href="https://www.privacypolicyonline.com/what-are-cookies/">"What Are Cookies"</a>.</p>

<h2>Google DoubleClick DART Cookie</h2>

<p>Google is one of a third-party vendor on our site. It also uses cookies, known as DART cookies, to serve ads to our site visitors based upon their visit to www.website.com and other sites on the internet. However, visitors may choose to decline the use of DART cookies by visiting the Google ad and content network Privacy Policy at the following URL – <a href="https://policies.google.com/technologies/ads">https://policies.google.com/technologies/ads</a></p>


<h2>Advertising Partners Privacy Policies</h2>

<P>You may consult this list to find the Privacy Policy for each of the advertising partners of speaksera.</p>

<p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on speaksera, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>

<p>Note that speaksera has no access to or control over these cookies that are used by third-party advertisers.</p>

<h2>Third Party Privacy Policies</h2>

<p>speaksera's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. </p>

<p>You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.</p>

<h2>CCPA Privacy Rights (Do Not Sell My Personal Information)</h2>

<p>Under the CCPA, among other rights, California consumers have the right to:</p>
<p>Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</p>
<p>Request that a business delete any personal data about the consumer that a business has collected.</p>
<p>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</p>
<p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>

<h2>GDPR Data Protection Rights</h2>

<p>We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:</p>
<p>The right to access – You have the right to request copies of your personal data. We may charge you a small fee for this service.</p>
<p>The right to rectification – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete.</p>
<p>The right to erasure – You have the right to request that we erase your personal data, under certain conditions.</p>
<p>The right to restrict processing – You have the right to request that we restrict the processing of your personal data, under certain conditions.</p>
<p>The right to object to processing – You have the right to object to our processing of your personal data, under certain conditions.</p>
<p>The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</p>
<p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>

<h2>Children's Information</h2>

<p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>

<p>speaksera does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>
<h3>Credit:</h3>
<p>The whole pricvacy policy content i have generated form this website <a href="https://www.privacypolicygenerator.info/">https://www.privacypolicygenerator.info/</a>
so if you want to generate privacy policy for your website you can visit here it is free of cost. Thank you</p><br>
{%endblock%}

templates/search_result.html
{%extends 'base.html'%}


{%block body%}
    
    <div class='container'>
    <h2>Search Result for  <small>'{{searched}}'</small></h2>
    
   <p> <a href={%url 'homeapp:home'%}> Back to Home page </a></p>

    There is {{count}} results for '{{searched}}'<br><br>
                    {%if result%}
                    {%for result in result%}

                

                    <p><a href={%url 'homeapp:article' result.slug%}>{{result.title}} </a> <small class='text-muted'>uploaded on {{result.date}}</small></p>
                    

                
            {%endfor%}

            {%else%}
                    <P>Sorry! No result found!</P>

            {%endif%}


        </div>

{%endblock%}


{%block footer%}
{%endblock%}